#cloud-config
package_update: true
packages:
  - nginx
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - bash -c 'echo "<h1>NGINX on $(hostname) - deployed by Terraform</h1>" > /var/www/html/index.html'
  - bash -c 'echo "Deployed at $(date -u)" >> /var/www/html/index.html'
